name: cashmeup
description: CashMeUp - anti boncos app
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  # atau bisa pakai '^3.9.0' jika kamu tahu versi Dart

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.5
  google_fonts: ^5.0.0
  # tambahkan nanti: fl_chart, firebase_core, cloud_firestore, dll

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
